const mongoose = require('mongoose');

const riskEventSchema = new mongoose.Schema(
  {
    employeeId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Employee',
      required: true,
      index: true,
    },
    ip: { type: String, required: true },
    deviceId: { type: String, required: true },
    action: {
      type: String,
      enum: ['LOGIN', 'DEPOSIT_CHANGE_ATTEMPT', 'BANK_ACCOUNT_CHANGE_ATTEMPT', 'ADDRESS_CHANGE_ATTEMPT', 'OTP_VERIFY', 'MANAGER_REVIEW', 'SIMULATED_ATTACK'],
      default: 'DEPOSIT_CHANGE_ATTEMPT',
    },
    riskScore: { type: Number, min: 0, max: 100, required: true },
    // e.g. ['MISMATCH_IP', 'NEW_DEVICE', 'BURST_ACTIVITY']
    riskCodes: { type: [String], default: [] },
    // Human-readable explanation generated by Gemini
    aiExplanation: { type: String, default: '' },
    // Gemini structured verdict
    geminiVerdict:         { type: String, enum: ['LIKELY_FRAUD', 'LIKELY_GENUINE', 'UNCERTAIN', ''], default: '' },
    geminiConfidence:      { type: Number, default: 0 },
    geminiRecommendation:  { type: String, default: '' },
    // Geo / metadata
    geo: { type: mongoose.Schema.Types.Mixed, default: {} },
    metadata: { type: mongoose.Schema.Types.Mixed, default: {} },
  },
  { timestamps: true }
);

// Compound index for aggregation pipeline performance
riskEventSchema.index({ employeeId: 1, createdAt: -1 });

module.exports = mongoose.model('RiskEvent', riskEventSchema);
